### ISSUE TITLE
Problems with using multiple training images

### ISSUE THREAD

**Issue by m03sina** [tomography/xlearn#14]
Hi,
I'm trying to run the training code with multiple training images and run into an error when executing mdl = train(). The code I'm using is as following:

`import dxchange`
`import matplotlib.pyplot as plt`
`from xlearn.transform import train`
`from xlearn.transform import model`
`import glob, os`

`batch_size = 400`
`nb_epoch = 10`
`#dim_img = 20`
`nb_filters = 32`
`nb_conv = 3`
`patch_step = 2`
`#patch_size = (dim_img, dim_img) `
`patch_size = (520, 472)`

`img_x=dxchange.read_tiff("SLS_raw_stack.tif")`
`img_y=dxchange.read_tiff("SLS_handSeg_stack.tif")`

`mdl = train(img_x, img_y, patch_size, patch_step, dim_img, nb_filters, nb_conv, batch_size, nb_epoch)`

Running the mdl=train() results in the error message "ValueError: Height of the patch should be less than the height of the image."

I tried changing the patch_size variable to patch_size = (3, 520, 472), but that ended in an error too.

Would anyone have an idea how to solve the problem? 
Cheers,
Sina

PS: the two test stacks (raw and segmented images) are attached in the zip
[Test_stacks.zip](https://github.com/tomography/xlearn/files/2310772/Test_stacks.zip)

**Comment by XYangXRay** [comment]
as the error message, the patch size should not be bigger than the image size. Patches are the small images extracted from the full image. It should be much smaller than the image size. Normally we use (32, 32) or (64, 64)

**Comment by m03sina** [comment]
Thanks for the suggestion. However putting the patch_size variable down to 20 (patch_size=(20,20)) did not resolve the problem. 
When I load the raw image stack into the img_x variable, it's shape is:
`print(img_x.shape)`
`(3, 520, 472)`
As I see it, the mdl=train() is not expecting a 3 * X * Y matrix as input but an X * Y (where X and Y refere to the image with and height) ? I wanted to test if reshaping the matrix to (520, 472, 3) would resolve the problem, however I haven't yet quite figured out how to get python to do this reshape propperly.

Cheers,
S

**Comment by m03sina** [comment]
I think I found the problem. Looking at the utils.extract functions (https://xlearn.readthedocs.io/en/latest/_modules/xlearn/utils.html#extract_3d) I saw that the `utils.extract_patches` that I had so far used is meant for 2D images and not 3D stacks. I exchanged `utils.extract_patches` with `utils.extract_3d` and the code now runs through it without an error. 
Cheers,
S

**Comment by m03sina** [comment]
I think I might have found the issue. I looked into the mdl = train() function (https://xlearn.readthedocs.io/en/latest/_modules/xlearn/transform.html#train) and saw that `img_input=` calls `utils.extract_patches`. Looking at the utils functions (https://xlearn.readthedocs.io/en/latest/_modules/xlearn/utils.html#extract_3d) I saw that `utils.extract_patches` expects a 2D image input and not a 3D stack. If I exchange the `utils.extract_patches` with `utils.extract_3d`, that part of the code runs through without an error. 

Cheers,
S

**Comment by m03sina** [comment]
I looked into the mdl = train() function (https://xlearn.readthedocs.io/en/latest/_modules/xlearn/transform.html#train) and saw that `img_input=` calls `utils.extract_patches`. Looking at the utils functions (https://xlearn.readthedocs.io/en/latest/_modules/xlearn/utils.html#extract_3d) I saw that `utils.extract_patches` expects a 2D image input and not a 3D stack? If I exchange the `utils.extract_patches` with `utils.extract_3d`, that part of the code runs through without an error (although I'm not sure if I'm allowed to exchange _patches for _3d). However, then the error occurs at the mdl.fit() function. Looking into it (https://github.com/tomography/xlearn/blob/master/xlearn/classify.py) seems like the mdl in classify is also only defined for a 2D image? 

Cheers,
S
