### ISSUE TITLE
minor issue, training input and testing input are the same

### ISSUE THREAD

**Issue by lzhengchun** [tomography/xlearn#16]
**test/test_data/ptrdict_test.tiff** which you used to test your trained model and **test/test_data/training_input.tiff** looks exactly the same, which means you test with training input which does not make sense and cannot validate if the mode is overfitted

**Comment by XYangXRay** [comment]
You are right. This should be two different images. There should be some confusions when I uploaded the files. I will fix it soon. In the meanwhile, you can also use the 'xlearn/test/seg_data/.' files to validate the model. Thank you for the nice advice.
