### ISSUE TITLE
Demand of permission to fixe errors due to old version of Keras

### ISSUE THREAD

**Issue by ZeliangSu** [tomography/xlearn#2]
Hello,
I have fixed these errors and now we can use it. Could you please give me the permission to pull a request?
Thx
Zeliang,

**Comment by dgursoy** [comment]
Hi @ZeliangSu. Thanks! I believe you can send a pull request from your forked repo to this one. Please let me know if you can't for some reason or have any issues.

**Comment by decarlof** [comment]
@ZeliangSu: thank you for the fix. More details on how to incorporate you contribution is at [fork&pull request](https://help.github.com/articles/creating-a-pull-request-from-a-fork/)
