### ISSUE TITLE
example transform_train.py fails to run

### ISSUE THREAD

**Issue by decarlof** [tomography/xlearn#6]
from xlearn.transform import train

fails with:

ValueError: You are tring to use the old GPU back-end. It was removed from Theano. Use device=cuda* now. See https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29 for more information.

**Comment by XYangXRay** [comment]
I tested it on my computer. It works. I think it is the reason that you restricted the backend of keras for your system. I remember we did it in previous. Now everything should work for tensorflow. For this case, you only to change it from the keras configure file ~/.keras/keras.json

**Comment by decarlof** [comment]
I modified ~/.keras/keras.json to:

{"epsilon": 1e-07, "floatx": "float32", "backend": "tensorflow"}

and I get a new error:

 /local/decarlo/conda/xlearn/xlearn/models.py

line 54 from tensorflow.python.keras.models import Sequential, Model
ImportError: No module named keras.models

I am using:    

    keras:      2.1.6-py27_0 conda-forge
    tensorflow: 1.3.0-py27_0 conda-forge

**Comment by XYangXRay** [comment]
It need tensorflow version later than 1.5. The old version just does not include keres.

**Comment by decarlof** [comment]
Ok I updated to tensorflow 1.8.0. running 

python doc/demo/transform_train.py

on a training set gives the following error:

/xlearn/utils.py", line 241, in extract_patches
TypeError: 'float' object cannot be interpreted as an integer

changing:  return patches.reshape((n_patches, p_h, p_w))
into: return patches.reshape((int(n_patches), p_h, p_w))

/xlearn/utils.py", line 241, in extract_patches
ValueError: cannot reshape array of size 19882800 into shape (49914,20,20)

**Comment by XYangXRay** [comment]
So far, I just updated and tested segmentation related files. The new way of segmentation works like this: https://github.com/tomography/xlearn/blob/master/doc/demo/segmentation_demo.py
I will remove the old transform related framework as the new version runs stably.

**Comment by ZeliangSu** [comment]
There might be a problem when you sample patches with _extracting function
49914 x 20 x 20= 19,965,600 !=19,882,800
Could you tell me the input image dimensions and you step size? I suppose that your patch size is 20.

**Comment by decarlof** [comment]
@ZeliangSu input image size is 1071 x 773
other parameters are:
batch_size = 800
nb_epoch = 10
dim_img = 20
nb_filters = 32
nb_conv = 3
patch_step = 4

**Comment by ZeliangSu** [comment]
@decarlof Ok I see. It's because of the int() which did a rounding. You need to change both  `/` into `//` in the lines 104, 105 for the compute_n_patch() and it will work perfectly.

**Comment by decarlof** [comment]
thanks all works now. I will push the changes as pull request
